<?xml version="1.0" encoding="utf-8"?><Database Name="SpeedyChef2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=titan.csse.rose-hulman.edu;Initial Catalog=SpeedyChef2;Persist Security Info=True;User ID=trottasn" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SpeedyChef2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="db_owner.Group_Member" Member="Group_Members">
    <Type Name="Group_Member">
      <Column Name="Memname" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Groupid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Member_Group_Group_Member" Member="Member_Group" ThisKey="Groupid" OtherKey="Groupid" Type="Member_Group" IsForeignKey="true" />
      <Association Name="Member_Group_Member" Member="Member" ThisKey="Memname" OtherKey="Memname" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Group_Tool" Member="Group_Tools">
    <Type Name="Group_Tool">
      <Column Name="Toolid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Groupid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Member_Group_Group_Tool" Member="Member_Group" ThisKey="Groupid" OtherKey="Groupid" Type="Member_Group" IsForeignKey="true" />
      <Association Name="Tool_Group_Tool" Member="Tool" ThisKey="Toolid" OtherKey="Toolid" Type="Tool" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Member_Group" Member="Member_Groups">
    <Type Name="Member_Group">
      <Column Name="Groupid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Groupadmin" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Groupname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Member_Group_Group_Member" Member="Group_Members" ThisKey="Groupid" OtherKey="Groupid" Type="Group_Member" />
      <Association Name="Member_Group_Group_Tool" Member="Group_Tools" ThisKey="Groupid" OtherKey="Groupid" Type="Group_Tool" />
      <Association Name="Member_Member_Group" Member="Member" ThisKey="Groupadmin" OtherKey="Memname" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Stove" Member="Stoves">
    <Type Name="Stove">
      <Column Name="Toolid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pwrtype" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Burnnum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tool_Stove" Member="Tool" ThisKey="Toolid" OtherKey="Toolid" Type="Tool" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Tool" Member="Tools">
    <Type Name="Tool">
      <Column Name="Toolid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Toolname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tooldesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Tool_Group_Tool" Member="Group_Tools" ThisKey="Toolid" OtherKey="Toolid" Type="Group_Tool" />
      <Association Name="Tool_Stove" Member="Stove" ThisKey="Toolid" OtherKey="Toolid" Type="Stove" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Food_Item" Member="Food_Items">
    <Type Name="Food_Item">
      <Column Name="Foodname" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Food_Item_Member_Allergen" Member="Member_Allergens" ThisKey="Foodname" OtherKey="Foodname" Type="Member_Allergen" />
      <Association Name="Food_Item_Member_Allergen1" Member="Member_Allergens1" ThisKey="Foodname" OtherKey="Substitution" Type="Member_Allergen" />
      <Association Name="Food_Item_Task_Food_Item" Member="Task_Food_Items" ThisKey="Foodname" OtherKey="Foodname" Type="Task_Food_Item" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="Memname" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mempass" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Member_Group_Member" Member="Group_Members" ThisKey="Memname" OtherKey="Memname" Type="Group_Member" />
      <Association Name="Member_Member_Group" Member="Member_Groups" ThisKey="Memname" OtherKey="Groupadmin" Type="Member_Group" />
      <Association Name="Member_Member_Allergen" Member="Member_Allergens" ThisKey="Memname" OtherKey="Memname" Type="Member_Allergen" />
      <Association Name="Member_Agenda" Member="Agenda" ThisKey="Memname" OtherKey="Agowner" Type="Agenda" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Member_Allergens" Member="Member_Allergens">
    <Type Name="Member_Allergen">
      <Column Name="Memname" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Foodname" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Substitution" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Food_Item_Member_Allergen" Member="Food_Item" ThisKey="Foodname" OtherKey="Foodname" Type="Food_Item" IsForeignKey="true" />
      <Association Name="Member_Member_Allergen" Member="Member" ThisKey="Memname" OtherKey="Memname" Type="Member" IsForeignKey="true" />
      <Association Name="Food_Item_Member_Allergen1" Member="Food_Item1" ThisKey="Substitution" OtherKey="Foodname" Type="Food_Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recipe" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="Recid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Recname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Recdesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Recipe_Recipe_Task" Member="Recipe_Tasks" ThisKey="Recid" OtherKey="Recid" Type="Recipe_Task" />
      <Association Name="Recipe_Task" Member="Tasks" ThisKey="Recid" OtherKey="Taskrec" Type="Task" />
      <Association Name="Recipe_Meal_Recipe" Member="Meal_Recipes" ThisKey="Recid" OtherKey="Recid" Type="Meal_Recipe" />
    </Type>
  </Table>
  <Table Name="dbo.Recipe_Tasks" Member="Recipe_Tasks">
    <Type Name="Recipe_Task">
      <Column Name="Recid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Taskid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Recipe_Recipe_Task" Member="Recipe" ThisKey="Recid" OtherKey="Recid" Type="Recipe" IsForeignKey="true" />
      <Association Name="Task_Recipe_Task" Member="Task" ThisKey="Taskid" OtherKey="Taskid" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="Taskrec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Taskid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Taskname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Taskdesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Tasktime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Task_Recipe_Task" Member="Recipe_Tasks" ThisKey="Taskid" OtherKey="Taskid" Type="Recipe_Task" />
      <Association Name="Task_Task_Food_Item" Member="Task_Food_Items" ThisKey="Taskid" OtherKey="Taskid" Type="Task_Food_Item" />
      <Association Name="Recipe_Task" Member="Recipe" ThisKey="Taskrec" OtherKey="Recid" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Task_Food_Items" Member="Task_Food_Items">
    <Type Name="Task_Food_Item">
      <Column Name="Taskid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Foodname" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Food_Item_Task_Food_Item" Member="Food_Item" ThisKey="Foodname" OtherKey="Foodname" Type="Food_Item" IsForeignKey="true" />
      <Association Name="Task_Task_Food_Item" Member="Task" ThisKey="Taskid" OtherKey="Taskid" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Meal" Member="Meals">
    <Type Name="Meal">
      <Column Name="Mealid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mealname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mealday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Mealsize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Meal_Meal_Recipe" Member="Meal_Recipes" ThisKey="Mealid" OtherKey="Mealid" Type="Meal_Recipe" />
      <Association Name="Meal_Agenda_Meal" Member="Agenda_Meals" ThisKey="Mealid" OtherKey="Mealid" Type="Agenda_Meal" />
    </Type>
  </Table>
  <Table Name="db_owner.Meal_Recipes" Member="Meal_Recipes">
    <Type Name="Meal_Recipe">
      <Column Name="Mealid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Recid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Meal_Meal_Recipe" Member="Meal" ThisKey="Mealid" OtherKey="Mealid" Type="Meal" IsForeignKey="true" />
      <Association Name="Recipe_Meal_Recipe" Member="Recipe" ThisKey="Recid" OtherKey="Recid" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="db_owner.Agenda_Meals" Member="Agenda_Meals">
    <Type Name="Agenda_Meal">
      <Column Name="Mealid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Agowner" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Meal_Agenda_Meal" Member="Meal" ThisKey="Mealid" OtherKey="Mealid" Type="Meal" IsForeignKey="true" />
      <Association Name="Agenda_Agenda_Meal" Member="Agenda" ThisKey="Agowner" OtherKey="Agowner" Type="Agenda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Agenda" Member="Agendas">
    <Type Name="Agenda">
      <Column Name="Agowner" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Agstartdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Agenddate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Agenda_Agenda_Meal" Member="Agenda_Meals" ThisKey="Agowner" OtherKey="Agowner" Type="Agenda_Meal" />
      <Association Name="Member_Agenda" Member="Member" ThisKey="Agowner" OtherKey="Memname" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="db_owner.SearchSingleKeyword" Method="SearchSingleKeyword">
    <Parameter Name="keyword" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="SearchSingleKeywordResult">
      <Column Name="Recid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Recname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Recdesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="db_owner.GetMealForDay" Method="GetMealForDay">
    <Parameter Name="user" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="date" Type="System.DateTime" DbType="Date" />
    <ElementType Name="GetMealForDayResult">
      <Column Name="Mealname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mealsize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Recname" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Recdesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>